"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l(l!5$)piz(sbu7c9*iuxze!wt3iqb9v^^ji^cp^9d4817%o6p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'LibraryProject.security_middleware.SecurityHeadersMiddleware',  # Custom security headers middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files (for profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ===============================
# SECURITY SETTINGS
# ===============================

# SECURITY WARNING: Set DEBUG to False in production
# DEBUG = False  # Enable this in production

# Security middleware settings
SECURE_BROWSER_XSS_FILTER = True  # Enables XSS filtering in browsers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevents MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevents page from being displayed in frame/iframe

# HTTPS settings (enable in production with SSL/TLS)
# SECURE_SSL_REDIRECT = True  # Redirects all HTTP requests to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # HTTP Strict Transport Security (1 year)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to subdomains
# SECURE_HSTS_PRELOAD = True  # Allow inclusion in HSTS preload lists

# Cookie security settings (enable in production with HTTPS)
# CSRF_COOKIE_SECURE = True  # CSRF cookie sent over HTTPS only
# SESSION_COOKIE_SECURE = True  # Session cookie sent over HTTPS only
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF cookie
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict SameSite policy for session cookies
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict SameSite policy for CSRF cookies

# Session security
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Sessions expire when browser closes
SESSION_COOKIE_AGE = 3600  # Session timeout in seconds (1 hour)

# Additional security headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Controls referrer information

# Content Security Policy (CSP) settings
# Basic CSP implementation without external dependencies
CSP_DEFAULT_SRC = "'self'"  # Only allow resources from same origin
CSP_SCRIPT_SRC = "'self' 'unsafe-inline'"  # Allow inline scripts (adjust as needed)
CSP_STYLE_SRC = "'self' 'unsafe-inline'"  # Allow inline styles (adjust as needed)
CSP_IMG_SRC = "'self' data: https:"  # Allow images from same origin, data URLs, and HTTPS
CSP_FONT_SRC = "'self' https:"  # Allow fonts from same origin and HTTPS
CSP_CONNECT_SRC = "'self'"  # Allow AJAX requests to same origin only
CSP_FRAME_ANCESTORS = "'none'"  # Prevent embedding in frames (same as X-Frame-Options: DENY)
